//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPermission
    {
        public int IdPermission { get; set; }
        public int IdRol { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string State { get; set; }
    
        public virtual TblPermission TblPermission { get; set; }
        public virtual TblRol TblRol { get; set; }
    }
}
