//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblModulos
    {
        public TblModulos()
        {
            this.TblMyModules = new HashSet<TblMyModules>();
            this.TblSections = new HashSet<TblSections>();
        }
    
        public int IdModules { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public Nullable<int> IdUserCreator { get; set; }
        public string image { get; set; }
    
        public virtual TblUsers TblUsers { get; set; }
        public virtual ICollection<TblMyModules> TblMyModules { get; set; }
        public virtual ICollection<TblSections> TblSections { get; set; }
    }
}
