//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblQuestion
    {
        public TblQuestion()
        {
            this.TblQuestionOptions = new HashSet<TblQuestionOptions>();
        }
    
        public int IdQuestion { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<int> IdForm { get; set; }
    
        public virtual CatTypeQuestion CatTypeQuestion { get; set; }
        public virtual TblForm TblForm { get; set; }
        public virtual ICollection<TblQuestionOptions> TblQuestionOptions { get; set; }
    }
}
