//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblQuestionOptions
    {
        public TblQuestionOptions()
        {
            this.UsersResponse = new HashSet<UsersResponse>();
        }
    
        public int IdQuestionOption { get; set; }
        public Nullable<int> IdQuestion { get; set; }
        public string Value { get; set; }
        public string OptionDesc { get; set; }
    
        public virtual TblQuestion TblQuestion { get; set; }
        public virtual ICollection<UsersResponse> UsersResponse { get; set; }
    }
}
