//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRol
    {
        public TblRol()
        {
            this.RolPermission = new HashSet<RolPermission>();
            this.TblUsersRol = new HashSet<TblUsersRol>();
        }
    
        public int IdRol { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<RolPermission> RolPermission { get; set; }
        public virtual ICollection<TblUsersRol> TblUsersRol { get; set; }
    }
}
