//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSections
    {
        public int IdSection { get; set; }
        public Nullable<int> IdModules { get; set; }
        public string Descripcion { get; set; }
        public string Title { get; set; }
        public string UrlContent { get; set; }
        public Nullable<int> IdType { get; set; }
    
        public virtual CatTypeSection CatTypeSection { get; set; }
        public virtual TblModulos TblModulos { get; set; }
    }
}
