//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsers
    {
        public TblUsers()
        {
            this.TblModulos = new HashSet<TblModulos>();
            this.TblMyModules = new HashSet<TblMyModules>();
            this.TblUsersRol = new HashSet<TblUsersRol>();
            this.UsersResponse = new HashSet<UsersResponse>();
        }
    
        public int IdUsers { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string State { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<TblModulos> TblModulos { get; set; }
        public virtual ICollection<TblMyModules> TblMyModules { get; set; }
        public virtual ICollection<TblUsersRol> TblUsersRol { get; set; }
        public virtual ICollection<UsersResponse> UsersResponse { get; set; }
    }
}
